apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "apimc.com.perficient/v1alpha1",
          "kind": "DevSecOpsManager",
          "metadata": {
            "name": "devsecopsmanager-sample"
          },
          "spec": {
            "config": {
              "repoPath": "",
              "repoUrl": ""
            },
            "forwarding": {
              "fluentd": {
                "affinity": {},
                "caFile": "files/default-openshift-logging-fluentd.crt",
                "image": "registry.redhat.io/openshift4/ose-logging-fluentd:v4.4",
                "keyFile": "files/default-openshift-logging-fluentd.key",
                "loglevel": "warn",
                "nodeSelector": {},
                "passphrase": "",
                "persistence": {
                  "accessMode": "ReadWriteOnce",
                  "enabled": false,
                  "size": "10Gi",
                  "storageClass": ""
                },
                "port": 24224,
                "replicas": 2,
                "resources": {
                  "limits": {
                    "cpu": "500m",
                    "memory": "1024Mi"
                  },
                  "requests": {
                    "cpu": "100m",
                    "memory": "512Mi"
                  }
                },
                "sharedkey": "splunkforwarding",
                "ssl": true,
                "tolerations": [],
                "updateStrategy": {
                  "type": "RollingUpdate"
                }
              },
              "preserveDefault": true
            },
            "fullnameOverride": "",
            "git": {
              "password": "",
              "server": "https://gitlab.com",
              "token": "",
              "username": ""
            },
            "nameOverride": "",
            "prometheus": {
              "token": ""
            }
          }
        },
        {
          "apiVersion": "apimc.com.perficient/v1alpha1",
          "kind": "ManagedNamespace",
          "metadata": {
            "name": "managednamespace-sample"
          },
          "spec": {
            "config": {
              "repoBranch": "master",
              "repoPath": "",
              "repoUrl": ""
            },
            "docker": {
              "password": "",
              "server": "https://quay.io",
              "username": ""
            },
            "fullnameOverride": "",
            "git": {
              "password": "",
              "server": "https://gitlab.com",
              "token": "",
              "username": ""
            },
            "manager": {
              "namespace": ""
            },
            "nameOverride": ""
          }
        },
        {
          "apiVersion": "apimc.com.perficient/v1alpha1",
          "kind": "SpringBootApp",
          "metadata": {
            "name": "springbootapp-sample"
          },
          "spec": {
            "autoscaling": {
              "enabled": false,
              "maxReplicas": 100,
              "minReplicas": 1,
              "targetCPUUtilizationPercentage": 80
            },
            "config": {
              "repo": ""
            },
            "docker": {
              "image": "",
              "repo": ""
            },
            "fullnameOverride": "",
            "git": {
              "branch": "master",
              "module": "",
              "url": ""
            },
            "management": {
              "port": 8081
            },
            "maven": {
              "mirror": ""
            },
            "nameOverride": "",
            "podAnnotations": {},
            "replicaCount": 1,
            "resources": {},
            "service": {
              "port": 8080
            },
            "serviceAccount": {
              "annotations": {}
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.3.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: devopsinabox.v0.0.28
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: DevSecOpsManager
      name: devsecopsmanagers.apimc.com.perficient
      version: v1alpha1
    - kind: ManagedNamespace
      name: managednamespaces.apimc.com.perficient
      version: v1alpha1
    - kind: SpringBootApp
      name: springbootapps.apimc.com.perficient
      version: v1alpha1
  description: Perficient's DevSecOps Manager For Kubernetes Applications
  displayName: Devops-in-a-box
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - apimc.com.perficient
          resources:
          - devsecopsmanagers
          - devsecopsmanagers/status
          - devsecopsmanagers/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          verbs:
          - '*'
        - apiGroups:
          - kibana.k8s.elastic.co
          resources:
          - kibanas
          verbs:
          - '*'
        - apiGroups:
          - logging.openshift.io
          resources:
          - logforwardings
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          - services
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - argoproj.io
          resources:
          - applications
          - argocds
          verbs:
          - '*'
        - apiGroups:
          - elasticsearch.k8s.elastic.co
          resources:
          - elasticsearches
          verbs:
          - '*'
        - apiGroups:
          - integreatly.org
          resources:
          - grafanadashboards
          - grafanadatasources
          - grafanas
          verbs:
          - '*'
        - apiGroups:
          - apimc.com.perficient
          resources:
          - managednamespaces
          - managednamespaces/status
          - managednamespaces/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - tekton.dev
          resources:
          - pipelines
          - tasks
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - prometheusrules
          - servicemonitors
          verbs:
          - '*'
        - apiGroups:
          - triggers.tekton.dev
          resources:
          - triggerbindings
          - triggertemplates
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - argoproj.io
          resources:
          - applications
          verbs:
          - '*'
        - apiGroups:
          - apimc.com.perficient
          resources:
          - springbootapps
          - springbootapps/status
          - springbootapps/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          - services
          verbs:
          - '*'
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - '*'
        - apiGroups:
          - triggers.tekton.dev
          resources:
          - eventlisteners
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: devopsinabox-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                - --leader-election-id=devopsinabox
                image: quay.io/mrethers/devopsinabox-operator:v0.0.28
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 90Mi
                  requests:
                    cpu: 100m
                    memory: 60Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - devops
  - devsecops
  - spring
  - boot
  - java
  - gitops
  - cicd
  - argo
  links:
  - name: Devopsinabox
    url: https://devopsinabox.domain
  maturity: alpha
  provider:
    name: Perficient Inc
    url: http://www.perficient.com
  version: 0.0.28
