apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-in-a-box-namespace.fullname" . }}-app-runner
imagePullSecrets:
  - name: {{ include "devops-in-a-box-namespace.fullname" . }}-pull-secret