kind: Secret
apiVersion: v1
metadata:
  name: {{ include "devops-in-a-box-namespace.fullname" . }}-git-auth
  namespace: {{ .Values.gitops.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: {{ .Values.config.repoUrl }}
  password: {{ .Values.git.password }}
  username: {{ .Values.git.username }}
type: kubernetes.io/basic-auth