kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: build-bot-scc
subjects:
  - kind: ServiceAccount
    name: {{ include "devops-in-a-box-namespace.fullname" . }}-build-bot
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole
