apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "devops-in-a-box-namespace.fullname" . }}-ecr-updater
rules:
- apiGroups: ["*"]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]