apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
  name: {{ include "devops-in-a-box-namespace.fullname" . }}-ecr-pull-secret
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "devops-in-a-box-namespace.fullname" . }}-ecr-updater
          containers:
          - command:
            - /bin/sh
            - -c
            - |-
              SECRET_NAME={{ include "devops-in-a-box-namespace.fullname" . }}-pull-secret
              oc delete secret --ignore-not-found ${SECRET_NAME}
              oc create secret docker-registry ${SECRET_NAME} \
              --docker-server=https://{{ .Values.aws.accountId }}.dkr.ecr.{{ .Values.aws.region }}.amazonaws.com \
              --docker-username=AWS \
              --docker-password=`aws ecr get-login-password --region {{ .Values.aws.region }}` \
              --docker-email="anymail.doesnt.matter@email.com"
              echo "Created secret $SECRET_NAME"
            env:
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.aws.region }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "devops-in-a-box-namespace.fullname" . }}-aws-secret
                  key: secretAccessKey
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "devops-in-a-box-namespace.fullname" . }}-aws-secret
                  key: accessKeyId
            image: quay.io/mrethers/rosa-installer:latest
            imagePullPolicy: Always
            name: ecr-cred-helper
          restartPolicy: Never
  schedule: 0 */6 * * *
  successfulJobsHistoryLimit: 1