apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-in-a-box-namespace.fullname" . }}-ecr-updater
secrets:
  - name: {{ include "devops-in-a-box-namespace.fullname" . }}-aws-secret