kind: Job
apiVersion: batch/v1
metadata:
  name: example2
  namespace: test
  uid: c96c8961-2c76-4dac-aeb9-3b1a01290ab0
  resourceVersion: '18008419'
  generation: 1
  creationTimestamp: '2022-02-18T20:07:18Z'
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  template:
    metadata:
      name: pi
      creationTimestamp: null
    spec:
      containers:
        - name: ecr-cred-helper
          image: 'quay.io/mrethers/rosa-installer:latest'
          command:
            - /bin/sh
            - '-c'
            - >-
              SECRET_NAME=test-devops-in-a-box-namespace-registry-auth

              echo "$SECRET_NAME"

              TOKEN=`aws ecr get-login-password --region us-east-1`

              TOKEN=`echo -n $TOKEN | base64 -w0`

              oc patch secret ${SECRET_NAME} --type=json -p="[{\"op\" :
              \"replace\" ,\"path\" : \"/data/password\" ,\"value\" :
              \"${TOKEN}\"}]"
          env:
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: test-devops-in-a-box-namespace-aws-secret
                  key: secretAccessKey
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: test-devops-in-a-box-namespace-aws-secret
                  key: accessKeyId
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: test-devops-in-a-box-namespace-ecr-updater
      serviceAccount: test-devops-in-a-box-namespace-ecr-updater
      securityContext: {}
      schedulerName: default-scheduler
  completionMode: NonIndexed
  suspend: false