kind: Secret
apiVersion: v1
metadata:
  name: {{ include "devops-in-a-box-namespace.fullname" . }}-pull-secret
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson