apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-in-a-box-namespace.fullname" . }}-build-bot
secrets:
  - name: {{ include "devops-in-a-box-namespace.fullname" . }}-git-auth
  - name: {{ include "devops-in-a-box-namespace.fullname" . }}-image-repo-creds