apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-updater
spec:
  params:
    - description: 'The driver to use for connecting, ''gitlab'' or ''github''.'
      name: driver
      type: string
    - default: ''
      description: >
        Required for private GitLab and Github installations  e.g.
        https://gitlab.example.com leave blank otherwise.
      name: api-endpoint
      type: string
    - description: Path within the source-repo to update
      name: file-path
      type: string
    - description: Image repo e.g. org/repo that is being updated
      name: image-repo
      type: string
    - description: 'Image URL to populate file with e.g. myorg/my-image:c2b4eff'
      name: new-image-url
      type: string
    - default: main
      description: Branch to fetch for updating
      name: source-branch
      type: string
    - description: Git repository to update e.g. org/repo
      name: source-repo
      type: string
    - description: >
        Prefix for naming automatically generated branch, if empty, this will
        update source-branch
      name: branch-generate-name
      type: string
    - description: >
        JSON path within the file-path to update e.g.
        spec.template.spec.containers.0.image
      name: update-key
      type: string
    - default: 'false'
      description: Allow insecure server connections when using SSL
      name: insecure
      type: string
  steps:
    - args:
        - update
        - '--driver=$(params.driver)'
        - '--file-path=$(params.file-path)'
        - '--image-repo=$(params.image-repo)'
        - '--new-image-url=$(params.new-image-url)'
        - '--source-branch=$(params.source-branch)'
        - '--source-repo=$(params.source-repo)'
        - '--update-key=$(params.update-key)'
        - '--branch-generate-name=$(params.branch-generate-name)'
        - '--api-endpoint=$(params.api-endpoint)'
        - '--insecure=$(params.insecure)'
      env:
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: image-updater-secret
      image: 'bigkevmcd/image-updater:latest'
      name: update-image
      resources: {}
