apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ include "devops-in-a-box-namespace.fullname" . }}
spec:
  params:
    # name of the app
    - default: 'myApp'
      name: APP_NAME
      type: string
    # git repo with app source code
    - default: 'https://github.com/myorg/myrepo'
      name: APP_REPO
      type: string
    # container repo
    - default: 'quay.io/myorg/myrepo'
      name: IMAGE_REPO
      type: string
    # namespace git repo for gitops
    - default: 'myorg/mykubeconfigrepo'
      name: CONFIG_REPO
      type: string
    # namespace git repo branch for gitops - staging env
    - default: master
      name: GIT_REVISION
      type: string
    # namespace git repo branch for gitops - prod env
    - default: master
      name: STAGE_CONFIG_BRANCH
      type: string
    - default: prod
      name: PROD_CONFIG_BRANCH
      type: string
    # the name of the field holding the container image in the CRD (Spring Boot/NodeJS/etc)
    - default: "spec.container.image"
      name: IMAGE_FIELD_NAME
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.APP_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: '$(params.IMAGE_REPO):$(params.GIT_REVISION)'
        - name: TLSVERIFY
          value: 'false'
        {{- if .Values.mirrors.maven }}
        - name: MAVEN_MIRROR_URL
          value: {{ .Values.mirrors.maven }}
        {{- end }}
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-java-1-5-0
      workspaces:
        - name: source
          workspace: workspace
    - name: update-stage-deployment-image
      params:
        - name: driver
          value: github
        - name: file-path
          value: $(params.APP_NAME).yaml
        - name: image-repo
          value: $(params.IMAGE_REPO)
        - name: new-image-url
          value: '$(params.IMAGE_REPO):$(params.GIT_REVISION)'
        - name: source-branch
          value: $(params.STAGE_CONFIG_BRANCH)
        - name: source-repo
          value: $(params.CONFIG_REPO)
        - name: update-key
          value: $(params.IMAGE_FIELD_NAME)
        - name: insecure
          value: 'true'
        - name: branch-generate-name
          value: ''
      runAfter:
        - build
      taskRef:
        kind: Task
        name: image-updater
    - name: update-prod-deployment-image
      params:
        - name: driver
          value: github
        - name: file-path
          value: $(params.APP_NAME).yaml
        - name: image-repo
          value: $(params.IMAGE_REPO)
        - name: new-image-url
          value: '$(params.IMAGE_REPO):$(params.GIT_REVISION)'
        - name: source-branch
          value: $(params.PROD_CONFIG_BRANCH)
        - name: source-repo
          value: $(params.CONFIG_REPO)
        - name: update-key
          value: $(params.IMAGE_FIELD_NAME)
        - name: insecure
          value: 'true'
        - name: branch-generate-name
          value: 'image-promotion-'
      runAfter:
        - build
      taskRef:
        kind: Task
        name: image-updater
  workspaces:
    - name: workspace
