apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: devopsinabox-github
spec:
  params:
  - name: git-repo-url
    value: $(body.resource.repository.remoteUrl)
  - name: git-revision
    value: $(body.resource.refUpdates[0].newObjectId)