apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: devopsinabox-github
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-revision
    value: $(body.resource.commits[0].commitId)