kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "net.fullname" . }}
  labels:
    {{- include "net.labels" . | nindent 4 }}
  annotations:
    {{- include "net.annotations" . | nindent 4 }}
    haproxy.router.openshift.io/disable_cookies: 'true'
spec:
  to:
    kind: Service
    name: {{ include "net.fullname" . }}
    weight: 100
  host: ""
  port:
    targetPort: http-service
  wildcardPolicy: None
status:
  ingress:
    - host: ""