# permissions for end users to view devsecopsmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devsecopsmanager-viewer-role
rules:
- apiGroups:
  - apimc.com.perficient
  resources:
  - devsecopsmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apimc.com.perficient
  resources:
  - devsecopsmanagers/status
  verbs:
  - get
