# permissions for end users to edit dotnetapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dotnetapp-editor-role
rules:
- apiGroups:
  - apimc.com.perficient
  resources:
  - dotnetapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apimc.com.perficient
  resources:
  - dotnetapps/status
  verbs:
  - get
