# permissions for end users to view managednamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managednamespace-viewer-role
rules:
- apiGroups:
  - apimc.com.perficient
  resources:
  - managednamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apimc.com.perficient
  resources:
  - managednamespaces/status
  verbs:
  - get
