apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for apimc.com.perficient/v1alpha1, Kind: DevSecOpsManager
##
- apiGroups:
  - apimc.com.perficient
  resources:
  - devsecopsmanagers
  - devsecopsmanagers/status
  - devsecopsmanagers/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterrolebindings"
  - "clusterroles"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "configmaps"
  - "secrets"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "argoproj.io"
  resources:
  - "applications"
  - "argocds"
- verbs:
  - "*"
  apiGroups:
  - "logging.openshift.io"
  resources:
  - "clusterlogforwarders"
- verbs:
  - "*"
  apiGroups:
  - "kibana.k8s.elastic.co"
  resources:
  - "kibanas"
- verbs:
  - "*"
  apiGroups:
  - "apimc.com.perficient"
  resources:
  - "springbootapps"
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "statefulsets"
- verbs:
  - "*"
  apiGroups:
  - "elasticsearch.k8s.elastic.co"
  resources:
  - "elasticsearches"
- verbs:
  - "*"
  apiGroups:
  - "integreatly.org"
  resources:
  - "grafanadashboards"
  - "grafanadatasources"
  - "grafanas"
- verbs:
  - "*"
  apiGroups:
  - "route.openshift.io"
  resources:
  - "routes"

##
## Rules for apimc.com.perficient/v1alpha1, Kind: ManagedNamespace
##
- apiGroups:
  - apimc.com.perficient
  resources:
  - managednamespaces
  - managednamespaces/status
  - managednamespaces/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "monitoring.coreos.com"
  resources:
  - "prometheusrules"
  - "servicemonitors"
- verbs:
  - "*"
  apiGroups:
  - "triggers.tekton.dev"
  resources:
  - "triggerbindings"
  - "triggertemplates"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "secrets"
  - "serviceaccounts"
- verbs:
  - "*"
  apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "rolebindings"
  - "roles"
- verbs:
  - "*"
  apiGroups:
  - "batch"
  resources:
  - "cronjobs"
- verbs:
  - "*"
  apiGroups:
  - "argoproj.io"
  resources:
  - "applications"
- verbs:
  - "*"
  apiGroups:
  - "tekton.dev"
  resources:
  - "pipelines"
  - "tasks"

##
## Rules for apimc.com.perficient/v1alpha1, Kind: SpringBootApp
##
- apiGroups:
  - apimc.com.perficient
  resources:
  - springbootapps
  - springbootapps/status
  - springbootapps/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "persistentvolumeclaims"
  - "services"
- verbs:
  - "*"
  apiGroups:
  - "apps.openshift.io"
  resources:
  - "deploymentconfigs"
- verbs:
  - "*"
  apiGroups:
  - "triggers.tekton.dev"
  resources:
  - "eventlisteners"
- verbs:
  - "*"
  apiGroups:
  - "route.openshift.io"
  resources:
  - "routes"

##
## Rules for apimc.com.perficient/v1alpha1, Kind: DotNetApp
##
- apiGroups:
  - apimc.com.perficient
  resources:
  - dotnetapps
  - dotnetapps/status
  - dotnetapps/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "deployments"
- verbs:
  - "*"
  apiGroups:
  - "route.openshift.io"
  resources:
  - "routes"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "services"

#+kubebuilder:scaffold:rules
- verbs:
  - "*"
  apiGroups:
  - "batch"
  resources:
  - "jobs"
