# permissions for end users to view springbootapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: springbootapp-viewer-role
rules:
- apiGroups:
  - apimc.com.perficient
  resources:
  - springbootapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apimc.com.perficient
  resources:
  - springbootapps/status
  verbs:
  - get
