kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "devops-in-a-box.fullname" . }}-argocd-managenamespaces
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: managednamespace-editor-role
