{{- if .Values.gitops }}
{{- if .Values.gitops.install }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "devops-in-a-box.fullname" . }}
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: {{ .Values.config.repoPath }}
    repoURL: {{ .Values.config.repoUrl }}
    targetRevision: HEAD
  syncPolicy:
    automated: {}
{{- end }}
{{- end }}