{{- if .Values.gitops }}
{{- if .Values.gitops.install }}
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: {{ include "devops-in-a-box.fullname" . }}
spec:
  server:
    route:
      enabled: true
{{- end }}
{{- end }}