{{- if .Values.gitops }}
{{- if .Values.gitops.install }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "devops-in-a-box.fullname" . }}-argocd
subjects:
  - kind: ServiceAccount
    name: {{ include "devops-in-a-box.fullname" . }}-argocd-application-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "devops-in-a-box.fullname" . }}-argocd
{{- end }}
{{- end }}
