kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "devops-in-a-box.fullname" . }}-argocd
subjects:
  - kind: ServiceAccount
    name: {{ include "devops-in-a-box.fullname" . }}-argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "devops-in-a-box.fullname" . }}-argocd
