kind: Secret
apiVersion: v1
metadata:
  name: {{ include "devops-in-a-box.fullname" . }}-git-auth
  annotations:
    tekton.dev/git-0: {{ .Values.git.server }}
data:
  password: {{ .Values.git.password | b64enc }}
  username: {{ .Values.git.username | b64enc }}
type: kubernetes.io/basic-auth