apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-in-a-box.fullname" . }}-grafana-token
  annotations:
    kubernetes.io/service-account.name: grafana-serviceaccount
type: kubernetes.io/service-account-token