kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "devops-in-a-box.fullname" . }}-monitoring
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: perficient-operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
