apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    {{- include "devops-in-a-box.annotations" . | nindent 4 }}
  name: {{ include "devops-in-a-box.fullname" . }}-kibana
  labels:
    {{- include "devops-in-a-box.labels" . | nindent 4 }}
spec:
  host: ""
  to:
    kind: Service
    name: {{ include "devops-in-a-box.fullname" . }}-kb-http
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status:
  ingress:
    - host: ""