kind: Service
apiVersion: v1
metadata:
  name: {{ template "devops-in-a-box.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: fluentd
{{ include "devops-in-a-box.labels" . | indent 4 }}
spec:
  ports:
    - name: 24224-tcp
      protocol: TCP
      port: 24224
      targetPort: 24224
  selector:
    app: {{ template "devops-in-a-box.fullname" . }}
  clusterIP: None
  sessionAffinity: None
