apiVersion: apimc.com.perficient/v1alpha1
kind: DevSecOpsManager
metadata:
  name: devsecopsmanager-sample
spec:
  # Default values copied from <project_dir>/helm-charts/devops-in-a-box/values.yaml
  config:
    repoPath: ""
    repoUrl: ""
  forwarding:
    fluentd:
      affinity: {}
      caFile: files/default-openshift-logging-fluentd.crt
      image: registry.redhat.io/openshift4/ose-logging-fluentd:v4.4
      keyFile: files/default-openshift-logging-fluentd.key
      loglevel: warn
      nodeSelector: {}
      passphrase: ""
      persistence:
        accessMode: ReadWriteOnce
        enabled: false
        size: 10Gi
        storageClass: ""
      port: 24224
      replicas: 2
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 512Mi
      sharedkey: splunkforwarding
      ssl: true
      tolerations: []
      updateStrategy:
        type: RollingUpdate
    preserveDefault: true
  fullnameOverride: ""
  git:
    password: ""
    server: https://gitlab.com
    token: ""
    username: ""
  gitops:
    install: true
  nameOverride: ""
  prometheus:
    token: ""
  
  
