# Default values for devops-in-a-box-namespace.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

git:
  username: ""
  password: ""
  
  # the operator requires the namespace config repo and apps all use the same git URL prefix
  baseurl: "https://gitlab.com"
  
ecr:
  accountId: "123456789415"
  region: "us-east-1"
  
container:
  registry: "https://quay.io"
  username: ""
  password: ""

config:
  # repoUrl needs to start with the git.baseurl parameter above
  repoUrl: ""
  repoPath: ""
  repoBranch: "master"

gitops:
  namespace: ""

# the name of the secret holding the maven settings file
maven:
  settings: ""

mirrors:
  maven: ""

nameOverride: ""
fullnameOverride: ""
